# curl -v -H 'Authorization: Basic YWRtaW46amF2YQ==' http://localhost:8080/messages

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: msg
              uri: http://127.0.0.1:8081
              predicates:
                - Path=/messages/**
              filters:
                - name: TokenRelay
                  args:
                    name: messaging-client

logging:
  level:
    org:
      nda:
        osp:
          web: TRACE
    org.springframework:
      cloud.gateway: DEBUG
      http.server.reactive: DEBUG
      web.reactive: DEBUG
      security: DEBUG
